/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Simple liveness probe for load balancers and CI. No auth required.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check (DB + Redis)
         * @description Verifies the database (and Redis, if configured) are reachable. Returns 503 if a dependency is down. No auth.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description A dependency is unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current authenticated user
         * @description Returns the caller's own profile only. RLS guarantees no other user's row is visible.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update own passenger profile
         * @description Self-service update of preferred language and accessibility needs.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProfile"];
                };
            };
            responses: {
                /** @description Updated profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/me/device-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Register a push (FCM) device token
         * @description Stores the caller's FCM token so proximity ("get ready") alerts can be pushed to their device.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DeviceToken"];
                };
            };
            responses: {
                /** @description Registered */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List companies (scoped by RLS)
         * @description Lists companies. super_admin sees all; company staff see only their own. Roles: super_admin, company_admin, manager.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Companies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompanyResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a company (super_admin only)
         * @description Creates a company (tenant). Restricted to super_admin.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCompany"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompanyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a company
         * @description Fetches one company by id (RLS-scoped to the caller).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Company */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompanyResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a company (super_admin or the company itself)
         * @description Updates company fields. super_admin, or the company's own company_admin.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCompany"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompanyResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stops (optionally filter by type)
         * @description Lists stations and stops (shared reference data, readable by any authenticated user). Filter with ?type=station|stop.
         */
        get: {
            parameters: {
                query?: {
                    type?: "station" | "stop";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stops */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StopResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a station or stop
         * @description Creates a station (no parent) or a stop (requires parentStationId). Geometry is synced from lat/lng automatically. Admins/managers.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateStop"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StopResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a stop
         * @description Fetches one stop/station by id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stop */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StopResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Archive a stop (soft-delete)
         * @description Archives a stop (hidden from lists, kept for history). Blocked while an active trip uses it or it still has child stops. Admins/managers.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archived */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StopResponse"];
                    };
                };
                /** @description Stop in active use */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a stop
         * @description Updates a stop's name, coordinates, or contact. Admins/managers.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateStop"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StopResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/fares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List RURA station-to-station fares
         * @description Lists the national fare matrix (station pair + amount), readable by any authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fares */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FareResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Upsert a fare (canonical ordering handled automatically)
         * @description Creates or updates the fare between two stations; ordering is normalized so direction does not matter. Admins/managers.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertFare"];
                };
            };
            responses: {
                /** @description Upserted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FareResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fares/between": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fare between two stations (either direction)
         * @description Returns the fare amount between two stations (checks both directions); null if none configured.
         */
        get: {
            parameters: {
                query: {
                    origin: string;
                    destination: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fare amount (null if none) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            fareAmount: number | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users (scoped by RLS to the caller company)
         * @description Lists users in the caller's company (super_admin sees all). Admins/managers.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user
         * @description Fetches one user by id (RLS-scoped).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Deactivate a user (soft-delete, admin)
         * @description Marks a user inactive (never hard-deleted, to preserve audit + integrity). Blocks their access.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deactivated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a user role or status (admin)
         * @description Updates a user's role or status. super_admin or company_admin. Takes effect on the user's next request.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUser"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite a staff user by email (admin)
         * @description Pre-creates a manager/agent/company_admin by email + role + company. They claim the row on first Clerk sign-in with that email — no second email entry.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InviteUser"];
                };
            };
            responses: {
                /** @description Invited */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Email or phone already in use */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List routes (scoped by RLS)
         * @description Lists the caller company's routes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Routes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a route with optional ordered stops
         * @description Creates a route (covers both directions) and optionally its ordered route_stops. Admins/managers.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateRoute"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a route with its stops
         * @description Fetches one route including its ordered stops.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Route */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Archive a route (soft-delete)
         * @description Archives a route (hidden from lists, kept for history). Blocked while it has an active trip. Admins/managers.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archived */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteResponse"];
                    };
                };
                /** @description Route has an active trip */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a route
         * @description Updates route fields (name, distance, schedule, status). Admins/managers.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateRoute"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List vehicles (scoped by RLS)
         * @description Lists the caller company's vehicles.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vehicles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VehicleResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Register a vehicle
         * @description Registers a vehicle (unique plate) optionally locked to a route. Admins/managers. Duplicate plate returns 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateVehicle"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VehicleResponse"];
                    };
                };
                /** @description Plate number already in use */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a vehicle
         * @description Fetches one vehicle by id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vehicle */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VehicleResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Archive a vehicle (soft-delete)
         * @description Archives a vehicle (hidden from lists, kept for history). Blocked while it is assigned to an active trip. Admins/managers.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archived */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VehicleResponse"];
                    };
                };
                /** @description Vehicle is on an active trip */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a vehicle
         * @description Updates a vehicle (route, capacity, status, odometer). Admins/managers.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateVehicle"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VehicleResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List trips (scoped by RLS)
         * @description Lists the caller company's trips, newest departure first.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trips */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TripResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a trip (instantiates trip_stops from the route)
         * @description Creates a live trip for a route and snapshots its stops from the route template (reversed for return trips). Staff.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTrip"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TripResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a trip with its stops
         * @description Fetches one trip including its ordered stops.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trip */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TripResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a trip (vehicle, driver, departure)
         * @description Updates a trip's vehicle, driver, departure time, or notes. Staff.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateTrip"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TripResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/trips/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Transition a trip status (validated lifecycle)
         * @description Moves a trip through scheduled -> boarding -> departed -> in_transit -> arriving -> completed (or cancelled). Illegal jumps return 400.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateTripStatus"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TripResponse"];
                    };
                };
                /** @description Illegal transition */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bookings (scoped by RLS; filter by tripId)
         * @description Lists bookings visible to the caller (own bookings for passengers, company bookings for staff). Filter with ?tripId=.
         */
        get: {
            parameters: {
                query?: {
                    tripId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bookings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a booking (overbooking-safe)
         * @description Books a seat on a trip segment: locks the trip, checks segment capacity, snapshots the fare, and stamps a daily ticket number. 409 if full, 422 if no fare. board/alight are trip_stop ids.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateBooking"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingResponse"];
                    };
                };
                /** @description No seats available */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No fare configured for this segment */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a booking
         * @description Fetches one booking by id (RLS-scoped).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a booking (frees the seat)
         * @description Cancels a booking and frees its segment. Blocked within the cancellation cutoff before departure unless an ops role passes override:true (recorded + audited).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CancelBooking"];
                };
            };
            responses: {
                /** @description Cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingResponse"];
                    };
                };
                /** @description Within cancellation cutoff */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Already cancelled */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            service: string;
            /** Format: date-time */
            timestamp: string;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string | null;
            phone: string;
            role: string;
            /** Format: uuid */
            companyId: string | null;
            status: string;
        };
        UpdateProfile: {
            preferredLanguage?: string;
            accessibilityNeeds?: string;
        };
        DeviceToken: {
            fcmToken: string;
        };
        CompanyResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string | null;
            phone: string | null;
            address: string | null;
            logoUrl: string | null;
            commissionRate: number;
            status: string;
            createdAt: string;
        };
        CreateCompany: {
            name: string;
            /** Format: email */
            email?: string;
            phone?: string;
            address?: string;
            /** Format: uri */
            logoUrl?: string;
            commissionRate?: number;
        };
        UpdateCompany: {
            name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            address?: string;
            /** Format: uri */
            logoUrl?: string;
            commissionRate?: number;
        };
        StopResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            type: string;
            /** Format: uuid */
            parentStationId: string | null;
            latitude: number;
            longitude: number;
            phone: string | null;
            address: string | null;
        };
        CreateStop: {
            name: string;
            /** @enum {string} */
            type: "station" | "stop";
            /** Format: uuid */
            parentStationId?: string | null;
            latitude: number;
            longitude: number;
            phone?: string;
            address?: string;
        };
        UpdateStop: {
            name?: string;
            latitude?: number;
            longitude?: number;
            phone?: string;
            address?: string;
        };
        FareResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            originStationId: string;
            /** Format: uuid */
            destinationStationId: string;
            fareAmount: number;
            fareSource: string;
        };
        UpsertFare: {
            /** Format: uuid */
            originStationId: string;
            /** Format: uuid */
            destinationStationId: string;
            fareAmount: number;
            /** @enum {string} */
            fareSource?: "manual" | "tapgo";
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string | null;
            phone: string;
            role: string;
            status: string;
            /** Format: uuid */
            companyId: string | null;
        };
        UpdateUser: {
            /** @enum {string} */
            role?: "super_admin" | "company_admin" | "manager" | "driver" | "agent" | "passenger";
            /** @enum {string} */
            status?: "active" | "inactive" | "suspended";
        };
        InviteUser: {
            /** Format: email */
            email: string;
            phone: string;
            name: string;
            /** @enum {string} */
            role: "company_admin" | "manager" | "agent";
            /** Format: uuid */
            companyId?: string;
        };
        RouteStopResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            stopId: string;
            stopOrder: number;
            distanceFromOriginKm: number | null;
        };
        RouteResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            name: string;
            origin: string;
            destination: string;
            distanceKm: number | null;
            estimatedDurationMin: number | null;
            departureTimes: string[];
            status: string;
            stops?: components["schemas"]["RouteStopResponse"][];
        };
        CreateRoute: {
            /** Format: uuid */
            companyId?: string;
            name: string;
            origin: string;
            destination: string;
            distanceKm?: number;
            estimatedDurationMin?: number;
            departureTimes?: string[];
            stops?: {
                /** Format: uuid */
                stopId: string;
                stopOrder: number;
                distanceFromOriginKm?: number;
            }[];
        };
        UpdateRoute: {
            name?: string;
            origin?: string;
            destination?: string;
            distanceKm?: number;
            estimatedDurationMin?: number;
            departureTimes?: string[];
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        VehicleResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            /** Format: uuid */
            routeId: string | null;
            plateNumber: string;
            model: string | null;
            capacity: number;
            year: number | null;
            status: string;
            currentKm: number | null;
        };
        CreateVehicle: {
            /** Format: uuid */
            companyId?: string;
            /** Format: uuid */
            routeId?: string | null;
            plateNumber: string;
            model?: string;
            capacity?: number;
            year?: number;
        };
        UpdateVehicle: {
            /** Format: uuid */
            routeId?: string | null;
            model?: string;
            capacity?: number;
            /** @enum {string} */
            status?: "active" | "maintenance" | "retired";
            currentKm?: number;
        };
        TripStopResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            stopId: string | null;
            stopName: string;
            stopOrder: number;
            status: string;
            estimatedArrival: string | null;
            actualArrival: string | null;
        };
        TripResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            /** Format: uuid */
            routeId: string;
            /** Format: uuid */
            vehicleId: string | null;
            /** Format: uuid */
            driverId: string | null;
            direction: string;
            departureTime: string;
            status: string;
            stops?: components["schemas"]["TripStopResponse"][];
        };
        CreateTrip: {
            /** Format: uuid */
            companyId?: string;
            /** Format: uuid */
            routeId: string;
            /** Format: uuid */
            vehicleId?: string | null;
            /** Format: uuid */
            driverId?: string | null;
            /** @enum {string} */
            direction?: "outbound" | "return";
            /** Format: date-time */
            departureTime: string;
        };
        UpdateTrip: {
            /** Format: uuid */
            vehicleId?: string | null;
            /** Format: uuid */
            driverId?: string | null;
            /** Format: date-time */
            departureTime?: string;
            delayReason?: string;
            notes?: string;
        };
        UpdateTripStatus: {
            /** @enum {string} */
            status: "scheduled" | "delayed" | "boarding" | "departed" | "in_transit" | "arriving" | "completed" | "cancelled";
            delayReason?: string;
        };
        BookingResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripId: string;
            /** Format: uuid */
            boardStopId: string;
            /** Format: uuid */
            alightStopId: string;
            passengerName: string;
            passengerPhone: string | null;
            fareAmount: number;
            paymentMethod: string | null;
            paymentStatus: string;
            status: string;
            dailyTicketNumberStation: number | null;
        };
        CreateBooking: {
            /** Format: uuid */
            tripId: string;
            /** Format: uuid */
            boardStopId: string;
            /** Format: uuid */
            alightStopId: string;
            /** Format: uuid */
            passengerId?: string | null;
            passengerName: string;
            passengerPhone?: string;
            /** @enum {string} */
            paymentMethod?: "cash" | "mobile_money";
            /** @enum {string} */
            bookingSource?: "tapgo" | "agent" | "app" | "walk_in";
        };
        CancelBooking: {
            reason?: string;
            override?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
